const OPTIONS_KEY = '$OPTIONS';
const PACKAGE_NAME = 'i18n-jsfp';
const SCOPE_DELIMITER = '.';
const SCOPE_PREFIX = '__TRANSLATIONS__';

export { OPTIONS_KEY, PACKAGE_NAME, SCOPE_DELIMITER, SCOPE_PREFIX };
